### ISSUE TITLE
set-output command has been deprecated by gh, needs new implementation

### ISSUE THREAD

**Issue by ghost** [yanglbme/actions-toolkit#12]
We use this library in our gh workflows, and started to get the following warning:

```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
Digging up, I noticed that the `set_output` function should issue a command in the form:
```bash
echo "{name}={value}" >> $GITHUB_OUTPUT
```
instead of:
```bash
echo "::set-output name={name}::{value}"
```

**Comment by yanglbme** [comment]
@cfierro-glb Thanks for your feedback.

I've released a new version. Please update actions-toolkit package to [v0.1.15](https://pypi.org/project/actions-toolkit/).

**Comment by ghost** [comment]
Thank you, amazing speed!
