### ISSUE TITLE
Output variables are not set

### ISSUE THREAD

**Issue by maksimu** [yanglbme/actions-toolkit#2]
Setting output variable using `core.set_output("KEY1", "VAL1")` does not seem to work when I'm trying to get output in the next steps likes this:

```
        run: |
          echo "${{ join(steps.sample-out.outputs.*, '\n') }}"
```

Do you happen to have complete example to set output and then retrieve it later in the future steps?

**Comment by maksimu** [comment]
Looks like it is a limitation of the Composite action. In JavaScript it will work as expected. See [THIS](https://github.community/t/dynamic-outputs-for-action/178457/3) answer for your reference

**Comment by yanglbme** [comment]
`set-output` command actually works in Composite action.

> If you use the `set-output` command in a workflow, it sets an output parameter but the workflow run's log does not show the command itself. If you enable command echoing, then the log shows the command, such as ::set-output name={name}::{value}.

> Command echoing is disabled by default. However, a workflow command is echoed if there are any errors processing the command.
