### ISSUE TITLE
Use of "file" attribute on warning and error messages

### ISSUE THREAD

**Issue by dballweg** [yanglbme/actions-toolkit#3]
I read through the source just to see if I was missing something, but it appears that the library does not support the file property on the annotation.  I currently just use print to make the warning message happen, but would love to switch to this library if you support adding the file property to the annotation.

**Comment by yanglbme** [comment]
Hi @dballweg , I release v0.0.8 just now, which supports the file property to the annotation. :)

#https://github.com/yanglbme/actions-toolkit/commit/53093997c7294a0bf8f17d8a5e4fe2006d4db83d
